language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
cache: bundler
before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
install: "bin/setup"
script: "bin/run-checks"
